/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package API.App.MobileWord;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import core.NetworkCommon;
import core.object.ItemList;
import core.object.Product;
import core.object.User;
import core.service.LoadProductService;
import core.service.LoginService;
import core.service.SignUpService;
import core.service.UserService;
import okhttp3.ResponseBody;
import retrofit2.Call;

public class LibraryTest {
	
	@Test
	public void testSomeLibraryMethod() throws InterruptedException, IOException {
		
		UserService ser = NetworkCommon.getRetrofit().create(UserService.class);
		Call<ResponseBody> call = ser.updatePersonalInfo(new User(17, "Donly Coann", null,
				null, null, null , "12039012324"));
		
		
		System.out.println(call.request());
		
		System.out.println(call.execute().body().string());

		//		
////		Map<String, String> params = new HashMap<String, String>();
////		params.put("keyword","OPPO");
////		params.put("offset", "1");
////		params.put("limit", "10");
//		Call<List<String>> call =ser.suggestion("OPPO");
//		
//		
//		System.out.println(call.request());
//		
//		
//		System.out.println("Body: " + call.execute().body().toString());
		
		
	}
	

}
